### ISSUE TITLE
"Remove message" bug(?)

### ISSUE THREAD

**Issue by pintoso** [jaqobb/message-editor#13]
I've been using message-editor for months, but after updating my server and the plugin I'm not able to remove messages 

for example if I use 
```
- ==: MessageEdit
  message-before-pattern: \{"translate":"commands\.gamemode\.success\.self"\,"with":\[\{"translate":"gameMode\.creative"\}\]\}
  message-before-place: SYSTEM_CHAT
  message-after: ''
  message-after-place: SYSTEM_CHAT
```
nothing changes 

but if i use 
```
- ==: MessageEdit
  message-before-pattern: \{"translate":"commands\.gamemode\.success\.self"\,"with":\[\{"translate":"gameMode\.creative"\}\]\}
  message-before-place: SYSTEM_CHAT
  message-after: test
  message-after-place: SYSTEM_CHAT
```
works

message-editor-2.4.2-all
paper 1.16.4 #404

**Comment by jaqobb** [comment]
Hey, I have been unable to reproduce this issue on my test server. Make sure you only edit this message once (and there are not multiple message edits that have the same message before pattern). You can also try updating Paper / reinstalling Message Editor. There is not much more I can suggest, sorry.
