### ISSUE TITLE
please Add Console message edit support thx

### ISSUE THREAD

**Issue by SwagPancakes** [jaqobb/message-editor#16]
please Add Console message edit support thx

**Comment by jaqobb** [comment]
What for if I may ask? Message Editor is intended to be used mostly if not only to change messages/stuff that the player (not an administrator) can see.

**Comment by SwagPancakes** [comment]
to change/remove console messages

**Comment by jaqobb** [comment]
What's the point of changing them? You can use another plugin specifically done to filter out console messages.
