### ISSUE TITLE
Add-ons for MessageEditor

### ISSUE THREAD

**Issue by datercero** [jaqobb/message-editor#17]
Hello, jaqobb!

Hope this finds you well. Just a quick note; thank you for this amazing plugin. You've really outdone it with this one, and I hope you bring more updates to the plugin.

The following are add-ons/features that the MessageEditor (ME) users would love to see in the plugin:
- **Simplification of JSON:** I tested ME to see if it can support JSON messages, and it does! Although, the JSON format is a bit complicated, especially for non-developers. I suggested simplifying the JSON format to a format similar or exact to when executing a /tellraw command. A website that I use (and I hope finds this useful for you) to create JSON messages is: minecraftjson.com. Of course, the versions at the bottom of the page must be considered for full compatibility with other Minecraft versions.
- **BungeeCord implementation:** I tested to see if there was a chance to edit BungeeCord messages/plugins, but no good there. As the purpose of this issue, I suggest adding a BungeeCord implementation to the plugin. For example, if I wish to edit a Bungee LuckPerms message, I would have the ability (with the rest of the other amazing, simplified features of ME) to edit those Bungee messages to what I want to replace it. Another example is the typical "No permissions" message that BungeeCord gives to players with no permissions; this implementation would grant me the ability to edit that "No permissions" message that BungeeCord default gives out to players.
- **Sound and Effects:** As the point suggest, adding sounds and particle effects to the ME system would probably freak out (in a good way) the ME community. Particle effects may be difficult, but adding the possibility to have sounds along the replaced message would be great.

For now, that would be all. If I get any ideas on the long run, I will let you know.

Once again, thank you for developing such an useful plugin.

**Comment by jaqobb** [comment]
Hey. Thank you for all the suggestions and while I appreciate all of them, I unfortunately will not be able to implement them. I have retired from Minecraft and everything that is Minecraft-related so I do not plan on updating this plugin or any other plugin I have created in the past anytime soon. That being said, I am still willing to merge pull requests if there are any and make an official resource update on the SpigotMC forum.
