### ISSUE TITLE
[Question] Single Word or Phrases Detecting

### ISSUE THREAD

**Issue by Maitlans** [jaqobb/message-editor#21]
Hello, I'm wondering if I'm able to detect single words or patterns within a message and be able to edit just those words rather than the full message.

Also I'm wondering if I can detect a message by words or a pattern and change the full message, because right now it seems you can only change messages which are detected in full rather than partially and I have messages I want to edit but they change constantly, if there's a way to change a full message via detecting a word or phrase please let me know as I'm unable to get it working. Thank you.

**Comment by jaqobb** [comment]
Hey,

> I'm wondering if I'm able to detect single words or patterns within a message and be able to edit just those words rather than the full message.

There is currently no way to do that. I had planned a custom placeholder system but that idea went down when I retired/lost interest in Minecraft. While I'm not really planning a new update for MessageEditor as of now, I'll be probably releasing a special version sometime after API for 1.17 is released which should contain this feature and possibly more.

> Also I'm wondering if I can detect a message by words or a pattern and change the full message, because right now it seems you can only change messages which are detected in full rather than partially and I have messages I want to edit but they change constantly

If only a part of your message changes (like a player name, some number, etc.) then you should be able to edit it by replacing that part of the message with a regular expression.
