### ISSUE TITLE
Error in 1.17 and Java 16 (I guess...)

### ISSUE THREAD

**Issue by CroaBeast** [jaqobb/message-editor#22]
Hi, I have this error spamming in the console everytime a player hits/kills a mob.
Link: https://paste.helpch.at/hiporifuli.rb

**Comment by jaqobb** [comment]
Update ProtocolLib.

**Comment by CroaBeast** [comment]
Using: Purpur 1.17.1 1261
Last Version of Message Editor: 2.4.6
Last Version of ProtocolLib: 4.7.0 in Spigot and Jenkins
Having a lot of errors.
https://paste.helpch.at/yegunugasa.rb

**Comment by kixmc** [comment]
I can also confirm this happens when there are bossbars present. Using the latest ProtocolLib

**Comment by jaqobb** [comment]
I can see this is most likely because 1.17 changed an enum to a class. I am personally unable to verify what's wrong exactly since I do not have Minecraft installed anymore.
