### ISSUE TITLE
an problem

### ISSUE THREAD

**Issue by veRonaldn** [jaqobb/message-editor#25]
Hello, i was be testing my server and found an problem. This problem is who an user can watch the message of the plugin "Click this message to start edit message" although I did not have permits  
[https://dunb17ur4ymx4.cloudfront.net/wysiwyg/1064865/45677a078d2acd1f5ab78969ecba17b848b84aa5.jpg](url). I love this plugin and I would like you to fix it 

(I speak Spanish, sorry for my English xd)

**Comment by veRonaldn** [comment]
This is error is with an tellraw

**Comment by jaqobb** [comment]
I do not plan on updating the plugin anytime soon. If this really is an issue with Message Editor, feel free to post a pull request with the fix. If accepted, the update will be posted to SpigotMC.
