### ISSUE TITLE
help with plugin

### ISSUE THREAD

**Issue by Elbry20** [jaqobb/message-editor#27]
I would like to know how I can replace the achievement messages that appear in the chat.
When I click on the message the interactive menu I get a different message from the achievement.

**Comment by jaqobb** [comment]
You can do it like with all the other messages. In case of achievement messages you have to either replace message for each achievement one by one or use regular expressions.

**Comment by Elbry20** [comment]
Could you give me an example please? It's that I have a mod server and every achievement of the mods appears in the chat and it's a bit annoying..

**Comment by Elbry20** [comment]
I have tried to put the variable of the player name with ({1,16}) and the achievement as ({1,25}) but it does not replace.
This is my example:
steps has made the advancement [Graves Key] > ({1,16}) has made the advancement ({1,25})
but it does not replace me

**Comment by jaqobb** [comment]
It does require some work and I currently have no time and also no longer provide support for the plugin. Using advanced message editing video available on resource's SpigotMC page as a baseline should be enough for you to do it on your own. 

The way you want to do it requires knowledge of regular expressions. You can either watch some tutorials or try using a website that allows you to create and test regular expressions (i.e. https://regex101.com/).
