### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by catboysalesman** [jaqobb/message-editor#29]
receiving this error on server start:
`18.11 23:35:16 [Server] ERROR Error occurred while enabling MessageEditor v2.4.12 (Is it up to date?)
18.11 23:35:16 [Server] INFO java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.accessors.FieldAccessor com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessorOrNull(java.lang.Class, java.lang.String, java.lang.Class)'
18.11 23:35:16 [Server] INFO at dev.jaqobb.message_editor.menu.MenuManager.constructArrowItem(MenuManager.java:228) ~[message-editor-2.4.12-all.jar:?]
18.11 23:35:16 [Server] INFO at dev.jaqobb.message_editor.menu.MenuManager.<clinit>(MenuManager.java:62) ~[message-editor-2.4.12-all.jar:?]
18.11 23:35:16 [Server] INFO at dev.jaqobb.message_editor.MessageEditorPlugin.onEnable(MessageEditorPlugin.java:128) ~[message-editor-2.4.12-all.jar:?]
18.11 23:35:16 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
18.11 23:35:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
18.11 23:35:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
18.11 23:35:16 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-234]
18.11 23:35:16 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-234]
18.11 23:35:16 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-234]
18.11 23:35:16 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-234]
18.11 23:35:16 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-234]
18.11 23:35:16 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-234]
18.11 23:35:16 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-234]
18.11 23:35:16 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
18.11 23:35:16 [Server] INFO [MessageEditor] Disabling MessageEditor v2.4.12`

any fix? thanks :)

**Comment by jaqobb** [comment]
It would appear that there's a missing method in your ProtocolLib version which is a mistake on my part since I did not consider that such a widely used method would be missing in the older versions.

The easiest and fastest fix for you would be to download and use ProtocolLib 5.0.0-SNAPSHOT (available here: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) which is also needed for the plugin to work on 1.19.

The slower fix would be to wait for me to release a new version but that might take same time since I am currently working on a minor update and not only some bug fixes.

**Comment by catboysalesman** [comment]
okay, i can do that. thanks for the reply!
