### ISSUE TITLE
Removing/Replacing edits

### ISSUE THREAD

**Issue by Metamfetamiin** [jaqobb/message-editor#33]
How do you replace or remove the edit you made?
There seems to be no command like /messageeditor delete (edit code) and then it would go back to its' original message.
When I try to replace the edit with the previous message or a newer edit, it doesn't let me because "There already is a edit that uses a file with the name of x".
Why not just let the user rewrite the edit or is this a bug?
I also don't understand what "override mode" and "replace mode" are supposed to be. "override mode" for me just replaces the message with the edit and "replace mode" just does nothing.
Thanks

**Comment by jaqobb** [comment]
> There seems to be no command like /messageeditor delete (edit code) and then it would go back to its' original message.

There is no such command at the moment and that is a mistake on my part, it will be added in a future update. Currently, to delete a message edit you can either prefix its file name with '#' or delete the file completely and then reload the plugin by using `/message-editor reload` command.

> Why not just let the user rewrite the edit or is this a bug?

A message can only be edited once. If you want to re-edit it, you have to completely delete its file, reload the plugin and then edit it one more time. I admit that the process can be improved and will be in a future update.

> I also don't understand what "override mode" and "replace mode" are supposed to be. "override mode" for me just replaces the message with the edit and "replace mode" just does nothing.

The main difference is that `override mode` replaces the entire message with the new one and `replace mode` only changes parts of it. I myself use `override mode` most of the times and I believe that `replace mode` was actually originally created just to correct some mistakes in the messages.

If it was not for the sake of trying to retain as much old functionalities as possible, I probably would have completely removed `replace mode` by now.

Before I close this issue, do let me know if there is further need to explain something.

**Comment by Metamfetamiin** [comment]
Thank you for the answer and I hope to see the process being improved in the future updates.
I already knew that was one of the ways to re-edit messages, just figured if there was a faster way to do it.

I am loving the plugin itself and It does pretty much everything I needed it to.
