### ISSUE TITLE
No GUI

### ISSUE THREAD

**Issue by mllr-mx** [jaqobb/message-editor#37]
Hi, I have tested your plugin. Unfortunately it does not work as presented. I can't click on any messages to get into the GUI. I tried with 2.5.0., 2.5.1. and 2.5.2. snapshot. I am at the current PaperMC version (#445) with ProtocolLib v5.0.0-SNAPSHOT-b612. The commands are displayed to me. But unfortunately no hover. Any ideas?

**Comment by jaqobb** [comment]
Hello, 

Let's start with first making sure these are true:
* There are no errors in the console,
* `attach-special-hover-and-click-events` setting in config.yml is set to `true`,
* You have `messageeditor.use` permission.

If there are still no hover messages, try using `/messageeditor activate game_chat system_chat` and check whether your messages are being correctly analyzed in the console (0:00 and 0:30 - 0:40 respectively, tutorial available here: https://www.youtube.com/watch?v=tUDvZOxwlok).

**Comment by mllr-mx** [comment]
_> There are no errors in the console_ 
 no Errors, the Plugin is loading with no Problems:
 
[13:35:14] [Server thread/INFO]: [MessageEditor] Enabling MessageEditor v2.5.1
[13:35:14] [Server thread/INFO]: [MessageEditor] Starting updater...
[13:35:14] [Server thread/INFO]: [MessageEditor] Starting menu manager...
[13:35:14] [Server thread/INFO]: [MessageEditor] Registering command...
[13:35:14] [Server thread/INFO]: [MessageEditor] Registering listeners...
[13:35:14] [Server thread/INFO]: [MessageEditor] Registering packet listeners...

_> attach-special-hover-and-click-events setting in config.yml is set to true
> packet-listeners.chat setting in config.yml is set to true_
Yes, both are true.

_> You have messageeditor.use permission_
In Luckperms I have assigned the permissives to my player. And the player also still has OP rights.

_> If there are still no hover messages, try using /messageeditor activate game_chat system_chat and check whether your messages are being correctly analyzed in the console_
Only the executed command is displayed in the console. 
[13:38:51 INFO]: m291 issued server command: /messageeditor activate GAME_CHAT SYSTEM_CHAT
In the game itself also says:
[Message Editor] You have activated analyzing 2 message place(s).

But no hover or gui-menu.

**Comment by jaqobb** [comment]
Alright, then just in case let's also verify whether the default edits work in the first place, that would be player join message and messages after using the `/version` command. You can view the default edits in the `edits` directory.

**Comment by mllr-mx** [comment]
I have the defaults in, but the new variant of the "join" does not work. But the new variant of "version" works. Here the last line is green.

**Comment by jaqobb** [comment]
I see. This makes it kind of hard to pinpoint the exact problem. Could you send your plugin list? You might have a plugin that changes the join message and also interacts with chat messages.

**Comment by mllr-mx** [comment]
I had already thought that and had accordingly deleted all plugins, except Luckperms. But the symptoms have been the same.

**Comment by mllr-mx** [comment]
If I read correctly, you already had it running under 1.19.3. There were only problems with Entity_Name. Do you remember which versions of PaperMC and ProtocolLib you had? Then I would start fresh and update successively until I found the error.

**Comment by jaqobb** [comment]
My current test server on which I confirmed the plugin working as intended runs on Spigot (not Paper) 3626 and ProtocolLib v5.0.0-SNAPSHOT-b608.

**Comment by mllr-mx** [comment]
I have tested it now. It's up to Paper. It looks like Paper is blocking some of it. There is also nothing in the config that affects it. With Spigot it worked immediately.

**Comment by jaqobb** [comment]
I see. In such case, I recommend using Spigot for the time being or wait for an update. I feel like I might know the reason behind Paper breaking the plugin but I'll have to investigate it later to confirm.

**Comment by jaqobb** [comment]
I have investigated the issue and found out the cause being [adventure](https://github.com/KyoriPowered/adventure) that Paper uses for its UI library.

Unfortunately, the changes that adventure makes are big and it would take some time to make Message Editor support Paper and due to my limited time, I am currently unable to create an update in a reasonable amount of time.

I will keep this issue open for the time being and hopefully revisit it once 1.20 is released.

**Comment by jaqobb** [comment]
Message Editor 2.5.2 has been released, fixing Paper issue and bumping ProtocolLib API among other things.
