### ISSUE TITLE
REMOVE THIS MESSAGE

### ISSUE THREAD

**Issue by SladeHazard** [jaqobb/message-editor#5]
https://gyazo.com/9f94f1c9fa387b2ecccf285d5eafd731
Am i able to remove this message from 1.7 users using this plugin if so how!
ty in advance

**Comment by jaqobb** [comment]
Hey, I'm sorry but 1.7 is not supported. You can try and just follow the [usage section](https://github.com/jaqobb/message-editor#usage) but I doubt this will work on 1.7.
