### ISSUE TITLE
Editing gui title/items

### ISSUE THREAD

**Issue by CodeDoctorDE** [jaqobb/message-editor#7]
nice to have 👍

it will be cool with combinding with #6 :D

**Comment by jaqobb** [comment]
Hey, I don't think this is in scope of this plugin but will see. No more information or ETA for now because I want to focus on other features first.

**Comment by jaqobb** [comment]
I haven't been able to do much in the project lately but after 1.5.0 is released (hopefully tomorrow), I will most likely start working on editing GUI titles/items in between editing more scoreboard stuff.
