### ISSUE TITLE
Some Console Error

### ISSUE THREAD

**Issue by Maitlans** [jaqobb/message-editor#8]
Hi, I recently updated to 1.16.4 and this error was not happening in 1.16.3, along with me updating I did update the plugin to the latest version, I'm not sure if it's either because the Minecraft version or because the new plugin update had some bug.
https://pastebin.com/Me01BRKK

Thought I'd add I sent a small donation for your hard work maintaining the plugin :D

**Comment by jaqobb** [comment]
Hey, thanks for the donation, really appreciate it. I believe I know what's the issue so in a few minutes after I test the new build it should be available on the SpigotMC forum. 

By the way, can you reproduce this issue and if so, could you tell me how to get this error to happen?
